In [1]:
# Basic data manipulation libraries
import pandas as pd
import numpy as np

# Visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Statistical testing
from scipy import stats

# For parsing JSON-like strings in TMDB dataset
import ast

# Set visualization style for cleaner plots
sns.set(style="whitegrid")

# Make plots appear inside notebook
%matplotlib inline

In [2]:
# Load datasets
movies = pd.read_csv(r"C:\Users\senak\Desktop\dsa210 project\data\raw\tmdb_5000_movies.csv")
credits = pd.read_csv(r"C:\Users\senak\Desktop\dsa210 project\data\raw\tmdb_5000_credits.csv")
bechdel = pd.read_csv(r"C:\Users\senak\Desktop\dsa210 project\data\raw\Bechdel_IMDB_Merge0524.csv")

# Check dataset shapes
print("Movies:", movies.shape)
print("Credits:", credits.shape)
print("Bechdel:", bechdel.shape)

Movies: (4803, 20)
Credits: (4803, 4)
Bechdel: (9718, 11)

In [ ]:
# Take a look at datasets

movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
bechdel.head()

,title,year,imdbid,id,bechdelRating,imdbAverageRating,numVotes,runtimeMinutes,genre1,genre2,genre3
0,Miss Jerry,1894,9.0,9779,0,5.4,212.0,45,Romance,NaN,NaN
1,"Story of the Kelly Gang, The",1906,574.0,1349,1,6.0,903.0,70,Action,Adventure,Biography
2,Cleopatra,1912,2101.0,2003,2,5.1,622.0,100,Drama,History,NaN
3,A Florida Enchantment,1914,3973.0,4457,2,5.8,300.0,63,Comedy,NaN,NaN
4,"Birth of a Nation, The",1915,4972.0,1258,2,6.1,26403.0,195,Drama,History,War

In [6]:
# Merge movies and credits datasets
# Both datasets share movie id

df = movies.merge(
    credits,
    left_on="id",
    right_on="movie_id"
)

# Check result
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
# Function to calculate female ratio from cast column

def get_female_ratio(cast):

    # Convert string to list
    cast = ast.literal_eval(cast)

    female_count = 0
    total_count = 0

    for person in cast:
        if person['gender'] == 1:
            female_count += 1
        total_count += 1

    # Avoid division by zero
    if total_count == 0:
        return 0

    return female_count / total_count


# Apply function
df['female_ratio'] = df['cast'].apply(get_female_ratio)

In [8]:
# Function to detect female director

def female_director(crew):

    crew = ast.literal_eval(crew)

    for person in crew:
        if person['job'] == "Director" and person['gender'] == 1:
            return 1

    return 0


# Apply
df['female_director'] = df['crew'].apply(female_director)

In [9]:
# Convert release date to datetime
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

# Extract year
df['year'] = df['release_date'].dt.year

In [ ]:
# After merging movies and credits datasets,
# pandas created title_x and title_y columns.
# I will keep the one coming from the movies dataset.

df = df.rename(columns={'title_x': 'title'})
df = df.drop(columns=['title_y'])

# quick check
df[['title', 'year']].head()

                                      title    year
0                                    Avatar  2009.0
1  Pirates of the Caribbean: At World's End  2007.0
2                                   Spectre  2015.0
3                     The Dark Knight Rises  2012.0
4                               John Carter  2012.0

In [11]:
# Clean title columns to reduce matching issues

df['title'] = df['title'].astype(str).str.strip()
bechdel['title'] = bechdel['title'].astype(str).str.strip()

# Convert years to numeric
df['year'] = pd.to_numeric(df['year'], errors='coerce')
bechdel['year'] = pd.to_numeric(bechdel['year'], errors='coerce')

In [12]:
# Merge TMDB data with Bechdel dataset

final_df = df.merge(
    bechdel,
    on=['title', 'year'],
    how='left'
)

print("Shape after merge:", final_df.shape)
final_df.head()

Shape after merge: (4805, 35)

,budget,genres,homepage,id_x,keywords,original_language,original_title,overview,popularity,production_companies,...,year,imdbid,id_y,bechdelRating,imdbAverageRating,numVotes,runtimeMinutes,genre1,genre2,genre3
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009.0,499549.0,582.0,3.0,7.9,1389834.0,162,Action,Adventure,Fantasy
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015.0,2379713.0,6519.0,1.0,6.8,467291.0,148,Action,Adventure,Thriller
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012.0,401729.0,3108.0,3.0,6.6,286786.0,132,Action,Adventure,Sci-Fi

In [13]:
# Check how many movies matched

matched = final_df['bechdelRating'].notna().sum()
total = len(final_df)

print("Matched movies:", matched)
print("Total movies:", total)
print("Match rate:", matched / total)

Matched movies: 1983
Total movies: 4805
Match rate: 0.41269510926118624

In [ ]:
# Keeping only the variables that will be useful for my analysis

final_df = final_df[[
    'title',
    'year',
    'budget',
    'revenue',
    'vote_average',
    'vote_count',
    'popularity',
    'female_ratio',
    'female_director',
    'bechdelRating',
    'imdbAverageRating',
    'numVotes',
    'runtimeMinutes',
    'genre1',
    'genre2',
    'genre3'
]]

final_df.head()

,title,year,budget,revenue,vote_average,vote_count,popularity,female_ratio,female_director,bechdelRating,imdbAverageRating,numVotes,runtimeMinutes,genre1,genre2,genre3
0,Avatar,2009.0,237000000,2787965087,7.2,11800,150.437577,0.144578,0,3.0,7.9,1389834.0,162,Action,Adventure,Fantasy
1,Pirates of the Caribbean: At World's End,2007.0,300000000,961000000,6.9,4500,139.082615,0.147059,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Spectre,2015.0,245000000,880674609,6.3,4466,107.376788,0.156627,0,1.0,6.8,467291.0,148,Action,Adventure,Thriller
3,The Dark Knight Rises,2012.0,250000000,1084939099,7.6,9106,112.312950,0.069620,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,John Carter,2012.0,260000000,284139100,6.1,2124,43.926995,0.222222,0,3.0,6.6,286786.0,132,Action,Adventure,Sci-Fi

In [15]:
# check missing values

final_df.isna().sum().sort_values(ascending=False)

genre3               3408
genre2               2962
bechdelRating        2822
imdbAverageRating    2822
numVotes             2822
runtimeMinutes       2822
genre1               2822
year                    1
title                   0
budget                  0
revenue                 0
vote_average            0
vote_count              0
popularity              0
female_ratio            0
female_director         0
dtype: int64

In [16]:
# remove unrealistic budgets

final_df = final_df[final_df['budget'] > 0]
final_df = final_df[final_df['revenue'] > 0]

print(final_df.shape)

(3231, 16)

In [18]:
# Save cleaned dataset for next notebook

final_df.to_csv("C:\\Users\\senak\\Desktop\\dsa210 project\\data\\processed\\movies_cleaned.csv", index=False)

print("Dataset saved successfully")

Dataset saved successfully